name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

#      - name: Log in to Azure Container Registry
#        uses: azure/docker-login@v1
#        with:
#          login-server: ${{ secrets.ACR_REGISTRY }}
#          username: ${{ secrets.ACR_USERNAME }}
#          password: ${{ secrets.ACR_PASSWORD }}
#
#      - name: Build and push Docker image
#        run: |
#          docker build -t ${{ secrets.ACR_REGISTRY }}/spring-cli:latest .
#          docker push ${{ secrets.ACR_REGISTRY }}/spring-cli:latest
